apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keda-operator
  namespace: monitoring
  labels:
    release: monitoring
    app: keda-operator
    area: monitoring
spec:
  namespaceSelector:
    matchNames:
      - keda
  selector:
    matchLabels:
      app.kubernetes.io/name: keda-operator
      app.kubernetes.io/instance: keda
  podMetricsEndpoints:
    - portNumber: 8080
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
