apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - opencost-ui-nodeport.yaml
  - prometheus-ui-nodeport.yaml

configMapGenerator:
  - name: cantaloupe-platform-overview
    namespace: monitoring
    files:
      - cantaloupe-platform-overview.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app: grafana
        area: monitoring
        platform: gcp
        cost-allocation: shared
      annotations:
        grafana-folder: Cantaloupe
  - name: cantaloupe-platform-overview-v1
    namespace: monitoring
    files:
      - cantaloupe-platform-overview-v1.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app: grafana
        area: monitoring
        platform: gcp
        cost-allocation: shared
      annotations:
        grafana-folder: Cantaloupe
