apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - opencost-ui-nodeport.yaml
  - prometheus-ui-nodeport.yaml
  - finops-recording-rules.yaml
  - onprem-rightsizing-rules.yaml
  - provider-recommendation-rules.yaml

configMapGenerator:
  - name: cantaloupe-platform-overview
    namespace: monitoring
    files:
      - cantaloupe-platform-overview.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app: grafana
        area: monitoring
        platform: gcp
        cost-allocation: shared
      annotations:
        grafana-folder: Cantaloupe
  - name: cantaloupe-kubernetes-finops
    namespace: monitoring
    files:
      - cantaloupe-kubernetes-finops.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app: grafana
        area: monitoring
        platform: gcp
        cost-allocation: shared
      annotations:
        grafana-folder: Cantaloupe
