apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - opencost-ui-nodeport.yaml
  - prometheus-ui-nodeport.yaml
  - allow-vpa-recommender-history.yaml
  - finops-recording-rules.yaml
  - onprem-rightsizing-rules.yaml
  - gcp-recommender-collector.yaml
  - aws-compute-optimizer-collector.yaml
  - vpa-recommendation-collector.yaml

configMapGenerator:
  - name: gcp-recommender-collector
    namespace: monitoring
    files:
      - gcp_recommender_collector.py
    options:
      labels:
        app: gcp-recommender-collector
        area: monitoring
        category: finops

  - name: aws-compute-optimizer-collector
    namespace: monitoring
    files:
      - aws_compute_optimizer_collector.py
    options:
      labels:
        app: aws-compute-optimizer-collector
        area: monitoring
        category: finops

  - name: vpa-recommendation-collector
    namespace: monitoring
    files:
      - vpa_recommendation_collector.py
    options:
      labels:
        app: vpa-recommendation-collector
        area: monitoring
        category: finops

  - name: cantaloupe-platform-overview
    namespace: monitoring
    files:
      - cantaloupe-platform-overview.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app: grafana
        area: monitoring
        platform: gcp
        cost-allocation: shared
      annotations:
        grafana-folder: Cantaloupe
  - name: cantaloupe-kubernetes-finops
    namespace: monitoring
    files:
      - cantaloupe-kubernetes-finops.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app: grafana
        area: monitoring
        platform: gcp
        cost-allocation: shared
      annotations:
        grafana-folder: Cantaloupe
