apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - runner-configmap.yaml
  - cronjobs.yaml
  - collector-configmap.yaml
  - collector-cronjob.yaml
  - collector-rbac.yaml
