apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: harbor-vault
  namespace: devops
spec:
  provider:
    vault:
      server: "https://cntlp-aws-vault-01.tail270b85.ts.net:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: eso-vault-approle
            key: roleId
          secretRef:
            name: eso-vault-approle
            key: secretId
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secrets
  namespace: devops
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: harbor-vault
    kind: SecretStore
  target:
    name: harbor-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRESQL_PASSWORD
      remoteRef:
        key: onp/harbor
        property: postgresql_password
    - secretKey: CORE_SECRET
      remoteRef:
        key: onp/harbor
        property: core_secret
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: onp/harbor
        property: jobservice_secret
    - secretKey: CSRF_KEY
      remoteRef:
        key: onp/harbor
        property: csrf_key
    - secretKey: REGISTRY_SECRET
      remoteRef:
        key: onp/harbor
        property: registry_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-config
  namespace: devops
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: harbor-vault
    kind: SecretStore
  target:
    name: harbor-registry-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yml: |
          version: 0.1
          log:
            level: info
          http:
            addr: :5000
            relativeurls: true
            drain_timeout: 60s
            secret: "{{ .REGISTRY_SECRET }}"
            debug:
              addr: :5001
          auth:
            token:
              issuer: harbor-token-issuer
              realm: http://cntlp-onp-wk-01.tail270b85.ts.net:31432/service/token
              rootcertbundle: /etc/registry/root.crt
              service: harbor-registry
          storage:
            cache:
              layerinfo: redis
            filesystem:
              rootdirectory: /storage
            maintenance:
              uploadpurging:
                enabled: true
                age: 168h
                interval: 24h
                dryrun: false
          redis:
            addr: harbor-redis:6379
            db: 1
  data:
    - secretKey: REGISTRY_SECRET
      remoteRef:
        key: onp/harbor
        property: registry_secret
