apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-core-config
  namespace: devops
data:
  app.conf: |
    appname = Harbor
    runmode = dev
    enableadmin = false

    ext_endpoint = https://cntlp-onp-wk-01.tail270b85.ts.net

    [cache]
    type = redis
    key = redis
    provider_config = addr=argocd-redis:6379,db=0
