apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-core
  namespace: devops
  labels:
    app: harbor-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-core
  template:
    metadata:
      labels:
        app: harbor-core
    spec:
      containers:
        - name: harbor-core
          image: goharbor/harbor-core:v2.10.0
          ports:
            - containerPort: 8080
          env:
            - name: CACHE_TYPE
              value: "redis"
            - name: REDIS_URL
              value: "redis://harbor-redis:6379/0" # 또는 argocd-redis:6379/0
            - name: PORT
              value: "8080"
