apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-core-config
  namespace: devops
data:
  app.conf: |
    appname = Harbor
    runmode = dev
    enableadmin = false
    
    [cache]
    type = redis
    key = harbor
    expire = 3600
    provider_config = redis://argocd-redis:6379/0
