apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-core
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-core
  template:
    metadata:
      labels:
        app: harbor-core
    spec:
      containers:
        - name: harbor-core
          image: goharbor/harbor-core:v2.10.0
          env:
            # 1. K8s 자동 주입 변수 덮어쓰기 (숫자 포트 명시)
            - name: POSTGRESQL_HOST
              value: "postgresql"
            - name: POSTGRESQL_PORT
              value: "5432"
            
            # 2. Redis 캐시 설정 (memory -> redis 변경)
            - name: CACHE_TYPE
              value: "redis"
            - name: REDIS_URL
              value: "redis://harbor-redis:6379/0"
              
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: harbor-data
              mountPath: /storage
      volumes:
        - name: harbor-data
          persistentVolumeClaim:
            claimName: harbor-data-pvc
