apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

resources:
  - harbor-service.yaml
  - harbor-components.yaml
  - harbor-core-config.yaml
  - redis.yaml
  - postgres.yaml
  - registry-config.yaml
  - portal.yaml
  - registry.yaml
  - pvc.yaml

patches:
  # 1. Harbor Service (Portal 80 포트로 확실히 연결)
  - target:
      kind: Service
      name: harbor
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: harbor
      spec:
        type: NodePort
        selector:
          app: harbor-portal
        ports:
          - name: http
            port: 80
            targetPort: 80
            nodePort: 31432

  # 2. Harbor Core (외부 접근 주소 지정)
  - target:
      kind: Deployment
      name: harbor-core
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: harbor-core
      spec:
        template:
          spec:
            containers:
              - name: harbor-core
                env:
                  - name: EXT_ENDPOINT
                    value: "https://cntlp-onp-wk-01.tail270b85.ts.net"
                  - name: HARBOR_URL
                    value: "https://cntlp-onp-wk-01.tail270b85.ts.net"
