apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

resources:
  - harbor-components.yaml
  - harbor-core-config.yaml

labels:
  - pairs:
      area: devops
      platform: onp
    includeSelectors: false

patches:
  - target:
      kind: (Deployment|StatefulSet)
    patch: |-
      kind: Dummy
      metadata:
        name: dummy
      spec:
        template:
          spec:
            nodeSelector:
              platform: onp
              role: devops

  - target:
      kind: Deployment
      name: harbor-core
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: harbor-core
      spec:
        template:
          spec:
            containers:
              - name: harbor-core
                env:
                  - name: CONFIG_PATH
                    value: "/etc/harbor/core"
                  - name: PORT
                    value: "8080"
                volumeMounts:
                  - name: config-volume
                    mountPath: /etc/harbor/core
            volumes:
              - name: config-volume
                configMap:
                  name: harbor-core-config
