apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-data-pvc
  namespace: devops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: harbor-data-pv
