apiVersion: v1
kind: Service
metadata:
  name: harbor-redis
  namespace: devops
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: harbor-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-redis
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-redis
  template:
    metadata:
      labels:
        app: harbor-redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: cntlp-onp-wk-01
      containers:
        - name: redis
          image: goharbor/redis-photon:v2.10.0
          ports:
            - containerPort: 6379
