apiVersion: v1
kind: Service
metadata:
  name: harbor-registry
  namespace: devops
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: harbor-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-registry
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-registry
  template:
    metadata:
      labels:
        app: harbor-registry
    spec:
      nodeSelector:
        kubernetes.io/hostname: cntlp-onp-wk-01
      containers:
        - name: registry
          image: goharbor/registry-photon:v2.10.0
          ports:
            - containerPort: 5000
