apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-registry-config
  namespace: devops
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    http:
      addr: :5000
      relativeurls: true
      drain_timeout: 60s
      secret: "HARBOR_REGISTRY_SECRET_123456"
      debug:
        addr: :5001
    auth:
      token:
        issuer: harbor-token-issuer
        realm: http://cntlp-onp-wk-01.tail270b85.ts.net:31432/service/token
        rootcertbundle: /etc/registry/root.crt
        service: harbor-registry
    storage:
      cache:
        layerinfo: redis
      filesystem:
        rootdirectory: /storage
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
    redis:
      addr: harbor-redis:6379
      db: 1

    # Registry push 이벤트를 Harbor Core의 내부 notification endpoint로 전달한다.
    notifications:
      endpoints:
        - name: harbor
          disabled: false
          url: http://harbor-core:8080/service/notifications
          timeout: 3000ms
          threshold: 5
          backoff: 1s
