apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor-vs
  namespace: devops
spec:
  hosts:
  - "*"
  gateways:
  - istio-ingress/istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: harbor-portal
        port:
          number: 80
