apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-vs
  namespace: devops
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/ingressgateway # 사용 중인 Gateway 이름 확인
  http:
  # 1. Harbor Portal (UI)
  - match:
    - uri:
        prefix: /harbor
    rewrite:
      uri: /
    route:
    - destination:
        host: harbor-portal.devops.svc.cluster.local
        port:
          number: 80

  # 2. Harbor Core API
  - match:
    - uri:
        prefix: /api
    - uri:
        prefix: /v2
    - uri:
        prefix: /service
    route:
    - destination:
        host: harbor.devops.svc.cluster.local
        port:
          number: 80
