apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - daemonset.yaml
  - allow-prometheus-scrape.yaml
  - allow-harbor-webhook.yaml
  - metrics-service.yaml
  - webhook-service.yaml
  - servicemonitor.yaml
  - prometheus-rule.yaml
  - events-configmap.yaml
  - events-deployment.yaml
