apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: audio-gateway
  namespace: audio-ingress
spec:
  selector:
    app: audio-ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - audio.example.com
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - audio.example.com
      tls:
        mode: SIMPLE
        credentialName: audio-tls
