apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcp-pd-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-standard
  replication-type: none
