apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audio-edge-smoke
  namespace: devops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/project-cantaloupe/02-k8s-manifests.git
    targetRevision: main
    path: platform/aws/audio-edge/base
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
