apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-storage
  namespace: devops
spec:
  project: default
  source:
    repoURL: https://github.com/project-cantaloupe/02-k8s-manifests.git
    targetRevision: main
    path: platform/gcp/csi-driver
  destination:
    server: https://kubernetes.default.svc
    namespace: storage-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
