apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-helm
  namespace: devops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.19.2
      helm:
        releaseName: harbor-v2
        valuesObject:
          expose:
            type: nodePort
            tls:
              enabled: false
            nodePort:
              name: harbor-v2
              ports:
                http:
                  port: 80
                  nodePort: 32432
          externalURL: http://cntlp-onp-wk-01.tail270b85.ts.net:32432
          existingSecretAdminPassword: harbor-v2-admin
          existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
          existingSecretSecretKey: harbor-v2-secret-key
          updateStrategy:
            type: Recreate
          persistence:
            enabled: true
            resourcePolicy: keep
            persistentVolumeClaim:
              registry:
                existingClaim: harbor-v2-registry
              jobservice:
                jobLog:
                  existingClaim: harbor-v2-jobservice
              database:
                existingClaim: harbor-v2-database
              redis:
                existingClaim: harbor-v2-redis
          trivy:
            enabled: false
          portal:
            nodeSelector: &onpNode
              platform: onp
              role: devops
          core:
            nodeSelector: *onpNode
          jobservice:
            nodeSelector: *onpNode
          registry:
            nodeSelector: *onpNode
          database:
            internal:
              nodeSelector: *onpNode
          redis:
            internal:
              nodeSelector: *onpNode
          exporter:
            nodeSelector: *onpNode
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=false
