apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-helm-storage
  namespace: devops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/project-cantaloupe/02-k8s-manifests.git
    targetRevision: main
    path: platform/onp/harbor-helm/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
