apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jenkins.yaml
  - harbor.yaml
  - gcp-storage.yaml
  - istio-base.yaml
  - istiod.yaml
  - monitoring-foundation.yaml
  - monitoring-stack.yaml
  - opencost.yaml
  - istio-ingress.yaml
  - test-logging.yaml
