apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-foundation
  namespace: devops
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/project-cantaloupe/02-k8s-manifests.git
    targetRevision: main
    path: platform/gcp/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
