apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: harbor-vault
  namespace: harbor-system
spec:
  provider:
    vault:
      server: "https://cntlp-aws-vault-01.tail270b85.ts.net:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: eso-vault-approle
            key: roleId
          secretRef:
            name: eso-vault-approle
            key: secretId
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-v2-admin
  namespace: harbor-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: harbor-vault
    kind: SecretStore
  target:
    name: harbor-v2-admin
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: onp/harbor
        property: harbor_admin_password
