apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

resources:
  - jenkins-deployment.yaml
  - virtualservice.yaml  # 신규 추가

labels:
  - pairs:
      area: devops
      platform: onp
    includeSelectors: false

patches:
  - target:
      kind: Deployment
      name: jenkins
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: jenkins
      spec:
        template:
          spec:
            nodeSelector:
              platform: onp
              role: devops
            containers:
            - name: jenkins
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  memory: 2Gi
