apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

resources:
  - pvc.yaml
  - jenkins.yaml

# Cantaloupe Pod/Resource 라벨 규칙 일괄 적용
labels:
  - pairs:
      area: devops
      platform: onp
    includeSelectors: false
