apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # <--- 이 줄을 반드시 추가해주세요!
  resources:
    requests:
      storage: 10Gi
