apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jenkins-vs
  namespace: devops
spec:
  hosts:
  - "cntlp-onp-wk-01.tail270b85.ts.net"
  gateways:
  - istio-ingress/istio-gateway
  http:
  - match:
    - uri:
        prefix: /jenkins
    route:
    - destination:
        host: jenkins.devops.svc.cluster.local
        port:
          number: 8080
