apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cantaloupe-platform-overview-preview
    namespace: monitoring
    files:
      - cantaloupe-platform-overview-preview.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app: grafana
        area: monitoring
        platform: gcp
        cost-allocation: shared
        deployment-track: preview
      annotations:
        grafana-folder: Cantaloupe Preview
