clusterName: "opensearch-cluster"
singleNode: true

# OpenSearch 실행 필수 커널 파라미터 (vm.max_map_count) 설정
extraInitContainers:
  - name: sysctl
    image: busybox:1.36
    command: ['sysctl', '-w', 'vm.max_map_count=262144']
    securityContext:
      privileged: true

persistence:
  enabled: true
  enableInitChown: true
  storageClass: "gcp-pd-sc"
  size: "30Gi"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"