#!/usr/bin/env python3
"""Generate non-secret Provider recommendation metrics for Prometheus."""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent
INPUT = ROOT / "provider-recommendations.yaml"
OUTPUT = ROOT.parent / "monitoring-foundation" / "provider-recommendation-rules.yaml"


def quoted(value: object) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def vector(value: float, labels: dict[str, object]) -> str:
    expr = f"vector({float(value):.9f})"
    for name, label_value in labels.items():
        expr = f'label_replace({expr}, "{name}", "{quoted(label_value)}", "", "")'
    return expr


def union(expressions: list[str], default: str = "vector(0)") -> str:
    return "\n  or\n".join(expressions) if expressions else default


def timestamp(value: str | None) -> float:
    if not value:
        return 0
    return datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp()


def render() -> str:
    data = yaml.safe_load(INPUT.read_text(encoding="utf-8"))
    info = []
    savings = []
    current_cpu = []
    recommended_cpu = []
    current_memory = []
    recommended_memory = []
    refresh = []
    provider_status = []

    for platform, provider in data.get("providers", {}).items():
        provider_status.append(vector(1, {"platform": platform, "status": provider["status"], "source": provider["source"]}))

    for item in data.get("recommendations", []):
        base = {
            "platform": item["platform"],
            "node": item["resource"],
            "current_profile": item["currentProfile"],
            "recommended_profile": item["recommendedProfile"],
            "source": item["source"],
            "state": item["state"],
            "priority": item["priority"],
        }
        info.append(vector(1, base))
        key = {"platform": item["platform"], "node": item["resource"], "source": item["source"]}
        savings.append(vector(item["estimatedMonthlySavingsUSD"], key))
        current_cpu.append(vector(item["currentVCPU"], key))
        recommended_cpu.append(vector(item["recommendedVCPU"], key))
        current_memory.append(vector(float(item["currentMemoryGiB"]) * 1024**3, key))
        recommended_memory.append(vector(float(item["recommendedMemoryGiB"]) * 1024**3, key))
        refresh.append(vector(timestamp(item.get("lastRefreshTime")), key))

    rules = [
        {"record": "cantaloupe:provider_recommender_status", "expr": union(provider_status)},
        {"record": "cantaloupe:provider_vm_recommendation_info", "expr": union(info)},
        {"record": "cantaloupe:provider_vm_estimated_monthly_savings", "expr": union(savings)},
        {"record": "cantaloupe:provider_vm_current_vcpu", "expr": union(current_cpu)},
        {"record": "cantaloupe:provider_vm_recommended_vcpu", "expr": union(recommended_cpu)},
        {"record": "cantaloupe:provider_vm_current_memory_bytes", "expr": union(current_memory)},
        {"record": "cantaloupe:provider_vm_recommended_memory_bytes", "expr": union(recommended_memory)},
        {"record": "cantaloupe:provider_vm_recommendation_last_refresh_timestamp_seconds", "expr": union(refresh)},
    ]
    resource = {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {
            "name": "cantaloupe-provider-vm-recommendations",
            "namespace": "monitoring",
            "labels": {"release": "monitoring", "app": "opencost", "area": "monitoring", "category": "finops"},
            "annotations": {"cantaloupe.io/recommendation-cache-version": data["version"]},
        },
        "spec": {"groups": [{"name": "cantaloupe.finops.provider-recommendations", "interval": "5m", "rules": rules}]},
    }
    return "# GENERATED by generate_provider_recommendations.py. Do not edit manually.\n" + yaml.safe_dump(resource, sort_keys=False, allow_unicode=True, width=140)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print("provider-recommendation-rules.yaml is stale")
            return 1
        print("provider-recommendation-rules.yaml is current")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"generated {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
