apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-data-pv
spec:
  capacity:
    storage: 100Gi  # PVC의 요청 용량 이상으로 설정 (필요시 수정)
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/harbor
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: platform
              operator: In
              values:
                - onp
            - key: role
              operator: In
              values:
                - devops
