apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.goharbor.io'
    chart: harbor
    targetRevision: 2.10.0  # 또는 최신 버전
    helm:
      values: |
        expose:
          type: nodePort
          tls:
            enabled: false
          nodePort:
            ports:
              http:
                nodePort: 30002
        externalURL: http://172.16.8.142:30002
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              size: 10Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
