apiVersion: v1
kind: Service
metadata:
  name: mesh-smoke
  namespace: apps
  labels:
    app: mesh-smoke
    area: apps
    platform: aws
spec:
  selector:
    app: mesh-smoke
  ports:
    - name: http
      port: 80
      targetPort: http
