apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mesh-smoke
  namespace: apps
spec:
  hosts:
    - "*"
  gateways:
    - audio-ingress/audio-gateway
  http:
    - route:
        - destination:
            host: mesh-smoke.apps.svc.cluster.local
            port:
              number: 80
